FROM python:3.6

WORKDIR /code

# Install tcp-port-wait.sh requirements
RUN apt-get update && apt-get install -y netcat

COPY ./requirements/base.txt requirements/base.txt
COPY ./requirements/dev.txt requirements/dev.txt
COPY ./requirements/production.txt requirements/production.txt

RUN pip install -r requirements/dev.txt

ADD . /code

ENTRYPOINT ["/code/docker-entrypoint-dev.sh"]
