# Generated by Django 2.0.5 on 2018-05-15 13:22

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(help_text='Filename', max_length=50)),
                ('file_type', models.CharField(blank=True, choices=[('jpg', 'JPG Image'), ('png', 'PNG Image'), ('pdf', 'PDF File')], help_text='Allowed File Types: jpg, png, pdf', max_length=30, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('organization_uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Organization UUID')),
                ('workflowlevel1_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), help_text='List of Workflowlevel1 UUIDs', size=None)),
                ('workflowlevel2_uuids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, help_text='List of Workflowlevel2 UUIDs', null=True, size=None)),
            ],
        ),
    ]
