# Generated by Django 2.0.5 on 2018-05-17 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='workflowlevel1_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, help_text='List of Workflowlevel1 UUIDs', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='document',
            name='workflowlevel2_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), default=['UUID'], help_text='List of Workflowlevel2 UUIDs', size=None),
            preserve_default=False,
        ),
    ]
