# Generated by Django 2.0.5 on 2018-06-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20180605_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contact_uuid',
            field=models.CharField(default='no-uuid', max_length=36, verbose_name='Contact UUID'),
            preserve_default=False,
        ),
    ]
