# Generated by Django 2.0.5 on 2018-08-08 14:34

import django.core.files.storage
from django.db import migrations, models
import document.models
import functools

try:
    from django_boto.s3.storage import S3Storage
    file_storage = S3Storage()
except AttributeError:
    from django.core.files.storage import FileSystemStorage
    file_storage = FileSystemStorage('/media/uploads/')


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20180612_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, storage=file_storage, upload_to=functools.partial(document.models.make_filepath_thumbnail, *('file',), **{})),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('jpg', 'JPG Image'), ('jpeg', 'JPEG Image'), ('png', 'PNG Image'), ('gif', 'GIF File'), ('pdf', 'PDF Document'), ('txt', 'TXT File'), ('doc', 'doc Document'), ('docx', 'docx Document'), ('xls', 'xls File'), ('xlsx', 'xlsx File'), ('ppt', 'ppt Document'), ('pptx', 'pptx Document')], help_text='Allowed File Types: jpg, jpeg, png, gif, pdf, txt, doc, docx, xls, xlsx, ppt, pptx', max_length=30, null=True),
        ),
    ]
