# Generated by Django 2.0.5 on 2018-11-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20180808_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contact_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Contact UUID'),
        ),
    ]
