# Generated by Django 2.0.5 on 2018-05-23 12:57

import django.contrib.postgres.fields
from django.db import migrations, models

import documents.models
import functools

try:
    from django_boto.s3.storage import S3Storage
    file_storage = S3Storage()
except AttributeError:
    from django.core.files.storage import FileSystemStorage
    file_storage = FileSystemStorage('/media/uploads/')


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20180517_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='User UUID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, storage=file_storage, upload_to=functools.partial(documents.models.make_filepath, *('file',), **{})),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='workflowlevel2_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, help_text='List of Workflowlevel2 UUIDs', null=True, size=None),
        ),
    ]
