# Generated by Django 2.0.5 on 2018-05-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20180523_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('jpg', 'JPG Image'), ('jpeg', 'JPEG Image'), ('png', 'PNG Image'), ('gif', 'GIF File'), ('pdf', 'PDF Document'), ('txt', 'TXT File'), ('doc', 'doc Document'), ('docx', 'docx Document'), ('xls', 'xls File'), ('xlsx', 'xlsx File'), ('xlsx', 'xlsx File'), ('ppt', 'ppt Document'), ('pptx', 'pptx Document')], help_text='Allowed File Types: jpg, jpeg, png, gif, pdf, txt, doc, docx, xls, xlsx, xlsx, ppt, pptx', max_length=30, null=True),
        ),
    ]
