# Generated by Django 2.0.5 on 2018-06-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20180529_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_description',
            field=models.CharField(blank=True, help_text='File Description', max_length=50, null=True),
        ),
    ]
