# Generated by Django 2.0.5 on 2019-01-23 15:19

from django.db import migrations, models
import documents.models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20181116_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(documents.models.make_filepath, *('file',), **{})),
        ),
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(documents.models.make_filepath_thumbnail, *('file',), **{})),
        ),
    ]
