# Generated by Django 2.0.5 on 2019-02-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20190123_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_description',
            field=models.CharField(blank=True, help_text='File Description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(help_text='Filename', max_length=200),
        ),
    ]
